"""Machine-readable agent-permissions artifact.

Writes `.coding-scaffold/agent-permissions.json` with the canonical permission shape from the
maintainer brief. The JSON is read by future eval checks and is referenced from AGENTS.md and
llms.txt as the authoritative "what the agent may touch" document.

The file is reviewable guidance, not a security boundary — actual enforcement belongs to the
coding tool, the OS, and the platform. The scaffold's role is to surface what *should* be
configured, in one place, in a format other tools can parse.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path


PERMISSIONS_RELATIVE = Path(".coding-scaffold") / "agent-permissions.json"


# Default read/write/deny patterns chosen for typical multi-language projects. Adjust per
# project by editing the generated file; the file is not regenerated unless the user runs
# `coding-scaffold permissions write --force`.
DEFAULT_READ_PATTERNS: tuple[str, ...] = (
    "src/**",
    "tests/**",
    "test/**",
    "docs/**",
    "README*",
    "CHANGELOG*",
    "pyproject.toml",
    "package.json",
    "Cargo.toml",
    "go.mod",
    ".coding-scaffold/**",
)

DEFAULT_WRITE_PATTERNS: tuple[str, ...] = (
    "src/**",
    "tests/**",
    "test/**",
    "docs/**",
)

DEFAULT_DENY_PATTERNS: tuple[str, ...] = (
    ".env",
    ".env.*",
    "secrets/**",
    ".coding-scaffold/.env.local",
    ".coding-scaffold/credentials.local.json",
    ".coding-scaffold/team/sources/**/_repo/.git/**",
    "build/**",
    "dist/**",
    "node_modules/**",
    ".git/**",
)

DEFAULT_REQUIRES_APPROVAL_COMMANDS: tuple[str, ...] = (
    "rm",
    "rm -rf",
    "sudo",
    "git push",
    "git push --force",
    "git reset --hard",
    "curl",
    "wget",
    "docker",
    "kubectl",
    "terraform",
    "npm publish",
    "pip install",
)


@dataclass(frozen=True)
class PermissionsResult:
    files: list[Path] = field(default_factory=list)
    skipped: list[Path] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, object]:
        return {
            "files": [str(p) for p in self.files],
            "skipped": [str(p) for p in self.skipped],
            "warnings": list(self.warnings),
        }


def default_permissions(target: Path) -> dict[str, object]:
    """Build the default permissions payload for a project, lightly project-aware."""

    root = target.expanduser().resolve()
    allowed_commands = _detect_allowed_commands(root)
    return {
        "$schema_version": 1,
        "description": (
            "Generated by `coding-scaffold permissions write`. Reviewable guidance for AI "
            "coding agents. Not a security boundary — enforcement belongs to the coding "
            "tool, the OS, the network layer, and the team's CI."
        ),
        "filesystem": {
            "read": list(DEFAULT_READ_PATTERNS),
            "write": list(DEFAULT_WRITE_PATTERNS),
            "deny": list(DEFAULT_DENY_PATTERNS),
        },
        "shell": {
            "allowed": allowed_commands,
            "requires_approval": list(DEFAULT_REQUIRES_APPROVAL_COMMANDS),
        },
        "network": "disabled_by_default",
        "mcp": {
            "remote_servers": "requires_approval",
            "unapproved_servers": "deny",
        },
    }


def write_agent_permissions(target: Path, *, force: bool = False) -> PermissionsResult:
    """Write `.coding-scaffold/agent-permissions.json`.

    By default, an existing file is skipped (so a team can hand-edit and not be overwritten).
    Pass `force=True` to regenerate from defaults.
    """

    root = target.expanduser().resolve()
    path = root / PERMISSIONS_RELATIVE
    files: list[Path] = []
    skipped: list[Path] = []
    if path.exists() and not force:
        skipped.append(path)
        return PermissionsResult(files=files, skipped=skipped)

    payload = default_permissions(root)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    files.append(path)
    return PermissionsResult(files=files, skipped=skipped)


def _detect_allowed_commands(root: Path) -> list[str]:
    """Pick a starter list of safe-by-default commands based on detected tooling."""

    commands: list[str] = []
    if (root / "pyproject.toml").exists():
        commands.extend(["pytest", "ruff", "ruff check", "python -m pytest"])
    if (root / "package.json").exists():
        commands.extend(["npm test", "npm run lint", "npx eslint", "npx prettier --check"])
    if (root / "Cargo.toml").exists():
        commands.extend(["cargo test", "cargo check", "cargo clippy"])
    if (root / "go.mod").exists():
        commands.extend(["go test ./...", "go vet ./..."])
    if (root / "Makefile").exists() or (root / "makefile").exists():
        commands.extend(["make test", "make lint"])
    if not commands:
        # Fall back to a minimal safe set.
        commands = ["git status", "git diff", "ls", "cat"]
    return sorted(set(commands))
